# Generated by Django 2.2.1 on 2019-06-17 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_recchoice_recquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec.RecQuestion'),
        ),
        migrations.DeleteModel(
            name='RecQuestion',
        ),
    ]
