# Generated by Django 2.2.1 on 2019-06-17 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190617_1150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecChoice',
        ),
    ]
