# Generated by Django 2.2.1 on 2019-06-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=4000)),
                ('state', models.CharField(max_length=2)),
                ('par_ver_code', models.CharField(max_length=128)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
