# Generated by Django 2.2.1 on 2019-06-22 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recml', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_name', models.CharField(max_length=200)),
                ('exec_order', models.IntegerField(max_length=10)),
                ('comments', models.CharField(max_length=4000)),
                ('state', models.CharField(max_length=128)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recml.Project')),
            ],
        ),
    ]
