# Generated by Django 2.2.1 on 2019-06-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recml', '0002_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='exec_order',
            field=models.IntegerField(),
        ),
    ]
